/* -----------------------------------------------------------------------------
 * javascript.swg
 *
 * Javascript typemaps
 * ----------------------------------------------------------------------------- */

%include <typemaps/swigmacros.swg>

%include <javascriptruntime.swg>

%include <javascriptstrings.swg>

%include <javascripthelpers.swg>

/* ------------------------------------------------------------
 *  Typemap specializations
 * ------------------------------------------------------------ */
%include <javascripttypemaps.swg>

%include <javascriptkw.swg>

%include <javascriptcode.swg>
